//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWarmPetWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Your name is required.")]
        [RegularExpression(@"^(?!\s)[a-zA-Z\s]{2,50}$", ErrorMessage = "Only alphabetic characters are allowed, enter at least two character.")]
        public string CustomerName { get; set; }
        [Required(ErrorMessage = "Your pet's name is required.")]
        [RegularExpression(@"^(?!\s)[a-zA-Z\s]{2,50}$", ErrorMessage = "Only alphabetic characters are allowed, enter at least two character.")]
        public string PetName { get; set; }
        [Required(ErrorMessage = "Your pet's type is required.")]
        [RegularExpression(@"^(?!\s)[a-zA-Z\s]{2,50}$", ErrorMessage = "Only alphabetic characters are allowed, enter at least two character.")]
        public string PetType { get; set; }
        [Required(ErrorMessage = "Your phone number is required.")]
        public int CustomerPhoneNumber { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public int VetId { get; set; }
        public string AspNetUsersId { get; set; }
    
        public virtual ConsultationTime ConsultationTime { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
