//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWarmPetWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ConsultationTime
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please Select a date and time.")]
        public System.DateTime DateAndTime { get; set; }
        [RegularExpression(@"((?:Booked)|(?:Free))", ErrorMessage ="Please enter 'Free' or 'Booked'.")]
        [Required(ErrorMessage = "Please enter Booking Status.")]
        public string BookingStatus { get; set; }
        public int VetId { get; set; }
    
        public virtual Vet Vet { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
