//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWarmPetWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Service> ServiceSet { get; set; }
        public virtual DbSet<Vet> VetSet { get; set; }
        public virtual DbSet<Review> ReviewSet { get; set; }
        public virtual DbSet<ConsultationTime> ConsultationTimeSet { get; set; }
        public virtual DbSet<Booking> BookingSet { get; set; }
    }
}
