//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWarmPetWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Review
    {
        public int Id { get; set; }
        
        [Required(ErrorMessage = "Please enter at less one character.")]
        public string ReviewTitle { get; set; }
        [Required(ErrorMessage = "Please enter at less one character.")]
        public string ReviewContent { get; set; }
        [Required(ErrorMessage = "Please choose a Rate.")]
        public double RateOfVet { get; set; }
        public string AspNetUsersId { get; set; }
        public int VetId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Vet Vet { get; set; }
    }
}
