//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWarmPetWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Service
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter at less one character.")]
        public string ServiceName { get; set; }
        [Required(ErrorMessage = "Please enter at less one character.")]
        public string ServiceCharacteristic { get; set; }
        [Required(ErrorMessage = "Please enter at less one character.")]
        public string ServiceDetail { get; set; }
    }
}
