//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWarmPetWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vet()
        {
            this.Review = new HashSet<Review>();
            this.ConsultationTime = new HashSet<ConsultationTime>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter vet's name.")]
        [RegularExpression(@"^(?!\s)[a-zA-Z\s]{2,50}$", ErrorMessage = "Only alphabetic characters are allowed, enter at least two character.")]

        public string VetName { get; set; }
        [Required(ErrorMessage = "Please enter vet's email.")]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage = "Please enter correct email format.")]
        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "Please enter phone number.")]  
        public int PhoneNumber { get; set; }
        [Required(ErrorMessage = "Please choose a rate.")]
        public double Rate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Review { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultationTime> ConsultationTime { get; set; }
    }
}
